# Adapter unit test with deliberately minimal fixtures, NOT an upstream build.
get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(work "${CMAKE_CURRENT_BINARY_DIR}/ekg_adapter_fixture")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/base/include" "${work}/base/src")
file(WRITE "${work}/base/include/grDef.h" "enum VAR { U_SYMAT5\n};\nconst char* names[] = {\"U_SYMAT5\"};\n")
file(WRITE "${work}/base/include/parameters.h" "const unsigned BSSN_NUM_VARS = 24;\nextern unsigned BSSN_REFINE_VARIABLE_INDICES[24];\n")
file(WRITE "${work}/base/src/grUtils.cpp" "void initialDataFunctionWrapper(double x,double y,double z,double* u) { u[0]=1; }\n")
file(WRITE "${work}/base/src/parameters.cpp" "void read() {\nstd::unordered_set<std::string> used_params;\n}\nvoid dump() {toml::value root = toml::table{};}\n")
file(WRITE "${work}/base/src/bssngr_main.cpp" "int main(){double var[24];bssn::readParamFile(argv[1], comm); ets->sync_with_mesh(); ctx->remesh(); if ((step % bssn::BSSN_GW_EXTRACT_FREQ)==0) extract();}\n")
file(WRITE "${work}/base/src/bssnCtx.cpp" "// grid_transfer is_remesh\nvoid f(){ bssn::isReMeshWAMR(x); DendroScalar var[bssn::BSSN_NUM_VARS]; }\n")
file(WRITE "${work}/base/src/rhs.cpp" "void bssnrhs(double** a,const double** b,const unsigned& off,const double* lo,const double* hi,const unsigned* sz,const unsigned& flag,double t,const double** c) { old(); }\n")
file(WRITE "${work}/base/src/physcon.cpp" "void physical_constraints(double** a,const double** b,unsigned off,const double* lo,const double* hi,const unsigned* sz,unsigned flag){ old(); }\n")
include("${root}/cmake/PrepareNative.cmake")
ekg_prepare_native("${work}/base" "${work}/native")
file(READ "${work}/native/src/rhs.cpp" rhs)
if(NOT rhs MATCHES "ekg::rhs_block\\(a, b, off, lo, hi, sz, flag, t\\)")
  message(FATAL_ERROR "RHS hook argument forwarding failed")
endif()
file(READ "${work}/native/include/parameters.h" h)
if(NOT h MATCHES "BSSN_REFINE_VARIABLE_INDICES\\[26\\]")
  message(FATAL_ERROR "Literal field-index array extension failed")
endif()
if(NOT h MATCHES "BSSN_NUM_VARS = 26;")
  message(FATAL_ERROR "26-field header extension failed")
endif()
file(READ "${work}/base/include/parameters.h" original)
if(NOT original MATCHES "BSSN_NUM_VARS = 24;")
  message(FATAL_ERROR "Adapter modified the original source")
endif()
message(STATUS "PASS: native adapter fixture, argument forwarding, field count, original preservation")

file(READ "${work}/native/src/bssngr_main.cpp" main)
if(NOT main MATCHES "ekg::event_due\\(step, bssn::BSSN_GW_EXTRACT_FREQ\\)")
  message(FATAL_ERROR "Optional event zero-frequency guard failed")
endif()
message(STATUS "PASS: native zero-frequency event guard")
