# Source-level adapter for the user's LOCAL experimental BSSN_GR application.
# It copies, never edits, that sibling application. Numerical mesh/RK/transfer
# methods are not replaced. Explicit hooks stop on an incompatible source layout.
function(ekg_replace_once variable old new label)
  set(t "${${variable}}")
  string(FIND "${t}" "${old}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "EKG native hook missing: ${label}. Inspect cmake/PrepareNative.cmake against your checkout.")
  endif()
  string(LENGTH "${old}" len)
  math(EXPR next "${pos}+${len}")
  string(SUBSTRING "${t}" ${next} -1 tail)
  string(FIND "${tail}" "${old}" another)
  if(NOT another EQUAL -1)
    message(FATAL_ERROR "EKG native hook is ambiguous: ${label}")
  endif()
  string(REPLACE "${old}" "${new}" t "${t}")
  set(${variable} "${t}" PARENT_SCOPE)
endfunction()

# Find a simple C++ function definition and recover its argument names. This is
# NOT a general C++ parser. These entry points have plain pointer/scalar args.
function(ekg_function variable name expected out_signature out_args)
  string(REGEX MATCH "void[ \t\r\n]+${name}[ \t\r\n]*\\(([^{}]*)\\)[ \t\r\n]*\\{" sig "${${variable}}")
  if(NOT sig)
    message(FATAL_ERROR "EKG could not identify void ${name}(...) definition")
  endif()
  set(args_text "${CMAKE_MATCH_1}")
  string(REPLACE "," ";" pieces "${args_text}")
  list(LENGTH pieces n)
  if(NOT n EQUAL expected)
    message(FATAL_ERROR "EKG ${name}: expected ${expected} plain arguments, found ${n}")
  endif()
  set(names)
  foreach(piece IN LISTS pieces)
    string(STRIP "${piece}" piece)
    string(REGEX MATCH "[a-zA-Z_][a-zA-Z_0-9]*$" arg "${piece}")
    if(arg STREQUAL "")
      message(FATAL_ERROR "EKG cannot parse argument of ${name}: ${piece}")
    endif()
    list(APPEND names "${arg}")
  endforeach()
  set(${out_signature} "${sig}" PARENT_SCOPE)
  set(${out_args} "${names}" PARENT_SCOPE)
endfunction()

function(ekg_prepare_native base dest)
  foreach(f include/grDef.h include/parameters.h src/grUtils.cpp src/parameters.cpp
            src/bssngr_main.cpp src/bssnCtx.cpp src/rhs.cpp src/physcon.cpp)
    if(NOT EXISTS "${base}/${f}")
      message(FATAL_ERROR "EKG requires ${base}/${f}; this is the experimental BSSN_GR layout")
    endif()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${base}/${f}")
  endforeach()
  file(MAKE_DIRECTORY "${dest}")
  file(COPY "${base}/" DESTINATION "${dest}" PATTERN "build" EXCLUDE
       PATTERN "CMakeFiles" EXCLUDE PATTERN ".git" EXCLUDE)

  file(READ "${base}/include/parameters.h" t)
  string(REGEX MATCH "BSSN_NUM_VARS[ \t]*=[ \t]*24[ \t]*;" old "${t}")
  if(NOT old)
    message(FATAL_ERROR "EKG expects an unmodified 24-field BSSN_GR base")
  endif()
  ekg_replace_once(t "${old}" "BSSN_NUM_VARS = 26;" "evolution count")
  file(WRITE "${dest}/include/parameters.h" "${t}")

  file(READ "${base}/include/grDef.h" t)
  string(REGEX MATCH "U_SYMAT5[ \t\r\n]*\\};" old "${t}")
  if(NOT old)
    message(FATAL_ERROR "EKG cannot find the final experimental VAR enum member U_SYMAT5")
  endif()
  ekg_replace_once(t "${old}" "U_SYMAT5,\n    U_SCALARPHI = 24,\n    U_SCALARPI = 25\n};" "field enum")
  ekg_replace_once(t "\"U_SYMAT5\"" "\"U_SYMAT5\", \"U_SCALARPHI\", \"U_SCALARPI\"" "field names")
  file(WRITE "${dest}/include/grDef.h" "${t}")

  file(READ "${base}/src/grUtils.cpp" t)
  set(t "#include \"ekg_native.h\"\n#include <algorithm>\n${t}")
  ekg_function(t initialDataFunctionWrapper 4 sig args)
  list(GET args 0 x)
  list(GET args 1 y)
  list(GET args 2 z)
  list(GET args 3 u)
  set(hook "\n    std::fill_n(${u}, bssn::BSSN_NUM_VARS, 0.0);\n    if(ekg::initialize_new_id(GRIDX_TO_X(${x}), GRIDY_TO_Y(${y}), GRIDZ_TO_Z(${z}), ${u})) return;\n")
  ekg_replace_once(t "${sig}" "${sig}${hook}" "new initial-data dispatch")
  file(WRITE "${dest}/src/grUtils.cpp" "${t}")

  file(READ "${base}/src/parameters.cpp" t)
  set(t "#include \"ekg_native.h\"\n${t}")
  string(REGEX MATCH "std::unordered_set<std::string>[ \t\r\n]+used_params;" old "${t}")
  if(NOT old)
    message(FATAL_ERROR "EKG cannot locate the experimental TOML used_params set")
  endif()
  ekg_replace_once(t "${old}" "${old}\n    ekg::read_config(parFile);\n    used_params.insert(\"EKG\");" "EKG TOML reader")
  string(REGEX MATCH "toml::value[ \t\r\n]+root[ \t]*=[ \t]*toml::table\\{\\};" old "${t}")
  if(old)
    ekg_replace_once(t "${old}" "${old}\n        root[\"EKG\"] = ekg::config_as_toml();" "EKG TOML dump")
  else()
    message(WARNING "No parameter-dump hook found: keep your input TOML and the build manifest")
  endif()
  file(WRITE "${dest}/src/parameters.cpp" "${t}")

  file(READ "${base}/src/bssngr_main.cpp" t)
  set(t "#include \"ekg_native.h\"\n${t}")
  string(REGEX REPLACE "var[ \t]*\\[[ \t]*24[ \t]*\\]" "var[bssn::BSSN_NUM_VARS]" t "${t}")
  string(REGEX MATCH "bssn::readParamFile\\(argv\\[1\\],[ \t\r\n]*comm\\);" old "${t}")
  if(NOT old)
    message(FATAL_ERROR "EKG cannot locate readParamFile(argv[1],comm) in the native driver")
  endif()
  ekg_replace_once(t "${old}" "${old}\n    ekg::validate_runtime(ts_mode, comm);" "native driver validation")
  string(REPLACE "bssnaeh::initialize_aeh();" "if(AEH::AEH_SOLVER_FREQ>0) bssnaeh::initialize_aeh();" t "${t}")
  string(REPLACE "bssnCtx->evolve_bh_loc();" "if(bssn::BSSN_ID_TYPE<100) bssnCtx->evolve_bh_loc();" t "${t}")
  string(REPLACE "bssnCtx->is_bh_merged(0.1)" "(bssn::BSSN_ID_TYPE<100 && bssnCtx->is_bh_merged(0.1))" t "${t}")
  # The attached native pattern uses (step % FREQUENCY)==0 without a
  # zero guard. Zero disables GW/checkpoint/fixed-mesh events in these par files.
  # Preserve nonzero scheduling and guard zero rather than changing any RK loop.
  string(REGEX REPLACE "\\(([A-Za-z_][A-Za-z_0-9]*)[ \t\r\n]*%[ \t\r\n]*(bssn::BSSN_[A-Z_]*FREQ[A-Z_]*)\\)[ \t\r\n]*==[ \t\r\n]*0"
    "ekg::event_due(\\1, \\2)" t "${t}")
  string(REGEX REPLACE "([A-Za-z_][A-Za-z_0-9]*)[ \t\r\n]*%[ \t\r\n]*(bssn::BSSN_[A-Z_]*FREQ[A-Z_]*)[ \t\r\n]*==[ \t\r\n]*0"
    "ekg::event_due(\\1, \\2)" t "${t}")
  if(t MATCHES "%[ \t\r\n]*bssn::BSSN_(REMESH_TEST_FREQ|GW_EXTRACT_FREQ|CHECKPT_FREQ)")
    message(FATAL_ERROR "Unrecognized native optional-event modulo expression: add an explicit zero-frequency guard")
  endif()
  if(NOT t MATCHES "sync_with_mesh" OR NOT t MATCHES "remesh")
    message(FATAL_ERROR "EKG cannot verify native remeshing/ETS mesh resynchronization in this driver")
  endif()
  file(WRITE "${dest}/src/bssngr_main.cpp" "${t}")

  file(READ "${base}/src/bssnCtx.cpp" t)
  set(t "#include \"ekg_native.h\"\n${t}")
  if(NOT t MATCHES "grid_transfer" OR NOT t MATCHES "is_remesh")
    message(FATAL_ERROR "EKG needs the native BSSNCtx AMR and grid-transfer methods")
  endif()
  string(REGEX REPLACE "(DendroScalar[ \t]+var[1]?[ \t]*\\[(bssn::)?BSSN_NUM_VARS\\])[ \t]*;" "\\1{};" t "${t}")
  if(NOT t MATCHES "bssn::isReMeshWAMR")
    message(FATAL_ERROR "EKG cannot locate bssn::isReMeshWAMR calls; wire the read-only normalization wrapper explicitly")
  endif()
  string(REPLACE "bssn::isReMeshWAMR" "ekg::isReMeshWAMR" t "${t}")
  string(REPLACE "bssn::addRemeshWAMR" "ekg::addRemeshWAMR" t "${t}")
  # Mesh tests, actual remeshing, DVector transfer, MPI context rebuild, and
  # ETS synchronization remain the native code, not a reimplementation.
  file(WRITE "${dest}/src/bssnCtx.cpp" "${t}")

  file(READ "${base}/src/rhs.cpp" t)
  set(t "#include \"ekg_native.h\"\n${t}")
  ekg_function(t bssnrhs 9 sig args)
  set(call "")
  foreach(k RANGE 0 7)
    list(GET args ${k} arg)
    if(k GREATER 0)
      string(APPEND call ", ")
    endif()
    string(APPEND call "${arg}")
  endforeach()
  ekg_replace_once(t "${sig}" "${sig}\n    ekg::rhs_block(${call});\n    return; // Native outer driver retained; generated EKG replaces this block RHS.\n" "generated block RHS")
  file(WRITE "${dest}/src/rhs.cpp" "${t}")

  file(READ "${base}/src/physcon.cpp" t)
  set(t "#include \"ekg_native.h\"\n${t}")
  ekg_function(t physical_constraints 7 sig args)
  string(JOIN ", " call ${args})
  ekg_replace_once(t "${sig}" "${sig}\n    ekg::constraints_block(${call});\n    return; // Constraint algebra is generated with the same matter model.\n" "generated constraints")
  file(WRITE "${dest}/src/physcon.cpp" "${t}")

  # Experimental revisions may spell these field-index arrays with literal
  # 24 rather than BSSN_NUM_VARS. Extend ONLY the known field-index arrays.
  foreach(f include/parameters.h src/parameters.cpp)
    file(READ "${dest}/${f}" t)
    string(REGEX REPLACE "(BSSN_(REFINE_VARIABLE_INDICES|VTU_OUTPUT_EVOL_INDICES))[ \t]*\\[[ \t]*24[ \t]*\\]" "\\1[26]" t "${t}")
    file(WRITE "${dest}/${f}" "${t}")
  endforeach()
  # Report other literal 24-entry buffers for explicit local review. Do not
  # rewrite arbitrary physics constants or unrelated arrays automatically.
  file(WRITE "${dest}/EKG_FIXED_SIZE_AUDIT.txt" "Literal [24] occurrences after adaptation; review their purpose:\n")
  file(GLOB_RECURSE audit_files "${dest}/include/*.h" "${dest}/src/*.cpp")
  foreach(f IN LISTS audit_files)
    file(STRINGS "${f}" matches REGEX "\\[[ \t]*24[ \t]*\\]")
    foreach(line IN LISTS matches)
      file(APPEND "${dest}/EKG_FIXED_SIZE_AUDIT.txt" "${f}: ${line}\n")
    endforeach()
  endforeach()

  file(WRITE "${dest}/EKG_NATIVE_ADAPTER.txt"
    "Native source basis: ${base}\n26-field private application copy. Original sibling unchanged.\nContext/RK/mesh/AMR implementation preserved. Inspect the eight changed files.\nConfigure recreates this copy. To edit it persistently set EKG_NATIVE_SOURCE_DIR to a separate copy.\n")
  file(WRITE "${dest}/EKG_SOURCE_HASHES.txt" "")
  foreach(f include/grDef.h include/parameters.h src/grUtils.cpp src/parameters.cpp
            src/bssngr_main.cpp src/bssnCtx.cpp src/rhs.cpp src/physcon.cpp)
    file(SHA256 "${base}/${f}" hash)
    file(APPEND "${dest}/EKG_SOURCE_HASHES.txt" "${f} ${hash}\n")
  endforeach()
endfunction()
