// ---------- AVX-512 macros (8 doubles per vector) ----------
// Designed to coexist with AVX2 variant in same TU by #undef'ing names
// before redefinition; typedef VEC is scoped to the body {} below.
#include <immintrin.h>
#undef VSET
#undef VLOAD
#undef VSTORE
#undef VADD
#undef VSUB
#undef VMUL
#undef VDIV
#undef VFMA
#undef VSQRT
#define VSET(x)      _mm512_set1_pd(x)
#define VLOAD(p)     _mm512_loadu_pd(p)
#define VSTORE(p,v)  _mm512_storeu_pd((p),(v))
#define VADD(a,b)    _mm512_add_pd((a),(b))
#define VSUB(a,b)    _mm512_sub_pd((a),(b))
#define VMUL(a,b)    _mm512_mul_pd((a),(b))
#define VDIV(a,b)    _mm512_div_pd((a),(b))
#define VFMA(a,b,c)  _mm512_fmadd_pd((a),(b),(c))
#define VSQRT(a)     _mm512_sqrt_pd(a)
// -----------------------------------------------------------

// BSSN RHS via bilinear cascade, AVX512-batched (8 grid points per batch)
// Generated by cascade_codegen.py -- do not edit  [FUSED-DERIVS]
// Included inside a harness wrapper that provides pointer setup + outer loops.
{
    typedef __m512d VEC;  // scoped to this body; coexists with other-width VEC in same TU
    // --- Stencil coefficient constants (per block) ---
    const double idx60    = (1.0/60.0)  / hx;
    const double idy60    = (1.0/60.0)  / hy;
    const double idz60    = (1.0/60.0)  / hz;
    const double idx2_180 = (1.0/180.0) / (hx*hx);
    const double idy2_180 = (1.0/180.0) / (hy*hy);
    const double idz2_180 = (1.0/180.0) / (hz*hz);
    
    // --- Unpack state (4 lanes at pp..pp+3) ---
    const VEC al = VLOAD(alpha+pp);
    const VEC ch = VLOAD(chi+pp);
    const VEC Kv = VLOAD(K+pp);
    const VEC be[3] = {VLOAD(beta0+pp), VLOAD(beta1+pp), VLOAD(beta2+pp)};
    const VEC Bv[3] = {VLOAD(B0+pp), VLOAD(B1+pp), VLOAD(B2+pp)};
    const VEC Gtv[3] = {VLOAD(Gt0+pp), VLOAD(Gt1+pp), VLOAD(Gt2+pp)};
    const VEC gt_sym6[6] = {VLOAD(gt0+pp), VLOAD(gt1+pp), VLOAD(gt2+pp),
                             VLOAD(gt3+pp), VLOAD(gt4+pp), VLOAD(gt5+pp)};
    const VEC gt[3][3] = {{gt_sym6[0], gt_sym6[1], gt_sym6[2]},
                           {gt_sym6[1], gt_sym6[3], gt_sym6[4]},
                           {gt_sym6[2], gt_sym6[4], gt_sym6[5]}};
    const VEC At_sym6[6] = {VLOAD(At0+pp), VLOAD(At1+pp), VLOAD(At2+pp),
                             VLOAD(At3+pp), VLOAD(At4+pp), VLOAD(At5+pp)};
    const VEC At[3][3] = {{At_sym6[0], At_sym6[1], At_sym6[2]},
                           {At_sym6[1], At_sym6[3], At_sym6[4]},
                           {At_sym6[2], At_sym6[4], At_sym6[5]}};
    
    // --- Unpack derivatives ---
    VEC d_al[3], d_ch[3], d_K[3];
    d_al[0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(alpha+pp+1), VLOAD(alpha+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(alpha+pp+2), VLOAD(alpha+pp-2)), VSUB(VLOAD(alpha+pp+3), VLOAD(alpha+pp-3)))));
    d_ch[0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(chi+pp+1), VLOAD(chi+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(chi+pp+2), VLOAD(chi+pp-2)), VSUB(VLOAD(chi+pp+3), VLOAD(chi+pp-3)))));
    d_K[0]  = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(K+pp+1), VLOAD(K+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(K+pp+2), VLOAD(K+pp-2)), VSUB(VLOAD(K+pp+3), VLOAD(K+pp-3)))));
    d_al[1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(alpha+pp+1*nx), VLOAD(alpha+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(alpha+pp+2*nx), VLOAD(alpha+pp-2*nx)), VSUB(VLOAD(alpha+pp+3*nx), VLOAD(alpha+pp-3*nx)))));
    d_ch[1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(chi+pp+1*nx), VLOAD(chi+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(chi+pp+2*nx), VLOAD(chi+pp-2*nx)), VSUB(VLOAD(chi+pp+3*nx), VLOAD(chi+pp-3*nx)))));
    d_K[1]  = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(K+pp+1*nx), VLOAD(K+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(K+pp+2*nx), VLOAD(K+pp-2*nx)), VSUB(VLOAD(K+pp+3*nx), VLOAD(K+pp-3*nx)))));
    d_al[2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(alpha+pp+1*(nx*ny)), VLOAD(alpha+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(alpha+pp+2*(nx*ny)), VLOAD(alpha+pp-2*(nx*ny))), VSUB(VLOAD(alpha+pp+3*(nx*ny)), VLOAD(alpha+pp-3*(nx*ny))))));
    d_ch[2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(chi+pp+1*(nx*ny)), VLOAD(chi+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(chi+pp+2*(nx*ny)), VLOAD(chi+pp-2*(nx*ny))), VSUB(VLOAD(chi+pp+3*(nx*ny)), VLOAD(chi+pp-3*(nx*ny))))));
    d_K[2]  = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(K+pp+1*(nx*ny)), VLOAD(K+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(K+pp+2*(nx*ny)), VLOAD(K+pp-2*(nx*ny))), VSUB(VLOAD(K+pp+3*(nx*ny)), VLOAD(K+pp-3*(nx*ny))))));
    VEC d_be[3][3];
    d_be[0][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(beta0+pp+1), VLOAD(beta0+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(beta0+pp+2), VLOAD(beta0+pp-2)), VSUB(VLOAD(beta0+pp+3), VLOAD(beta0+pp-3)))));
    d_be[0][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(beta0+pp+1*nx), VLOAD(beta0+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(beta0+pp+2*nx), VLOAD(beta0+pp-2*nx)), VSUB(VLOAD(beta0+pp+3*nx), VLOAD(beta0+pp-3*nx)))));
    d_be[0][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(beta0+pp+1*(nx*ny)), VLOAD(beta0+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(beta0+pp+2*(nx*ny)), VLOAD(beta0+pp-2*(nx*ny))), VSUB(VLOAD(beta0+pp+3*(nx*ny)), VLOAD(beta0+pp-3*(nx*ny))))));
    d_be[1][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(beta1+pp+1), VLOAD(beta1+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(beta1+pp+2), VLOAD(beta1+pp-2)), VSUB(VLOAD(beta1+pp+3), VLOAD(beta1+pp-3)))));
    d_be[1][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(beta1+pp+1*nx), VLOAD(beta1+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(beta1+pp+2*nx), VLOAD(beta1+pp-2*nx)), VSUB(VLOAD(beta1+pp+3*nx), VLOAD(beta1+pp-3*nx)))));
    d_be[1][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(beta1+pp+1*(nx*ny)), VLOAD(beta1+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(beta1+pp+2*(nx*ny)), VLOAD(beta1+pp-2*(nx*ny))), VSUB(VLOAD(beta1+pp+3*(nx*ny)), VLOAD(beta1+pp-3*(nx*ny))))));
    d_be[2][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(beta2+pp+1), VLOAD(beta2+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(beta2+pp+2), VLOAD(beta2+pp-2)), VSUB(VLOAD(beta2+pp+3), VLOAD(beta2+pp-3)))));
    d_be[2][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(beta2+pp+1*nx), VLOAD(beta2+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(beta2+pp+2*nx), VLOAD(beta2+pp-2*nx)), VSUB(VLOAD(beta2+pp+3*nx), VLOAD(beta2+pp-3*nx)))));
    d_be[2][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(beta2+pp+1*(nx*ny)), VLOAD(beta2+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(beta2+pp+2*(nx*ny)), VLOAD(beta2+pp-2*(nx*ny))), VSUB(VLOAD(beta2+pp+3*(nx*ny)), VLOAD(beta2+pp-3*(nx*ny))))));
    VEC d_Gt[3][3];
    d_Gt[0][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(Gt0+pp+1), VLOAD(Gt0+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(Gt0+pp+2), VLOAD(Gt0+pp-2)), VSUB(VLOAD(Gt0+pp+3), VLOAD(Gt0+pp-3)))));
    d_Gt[0][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(Gt0+pp+1*nx), VLOAD(Gt0+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(Gt0+pp+2*nx), VLOAD(Gt0+pp-2*nx)), VSUB(VLOAD(Gt0+pp+3*nx), VLOAD(Gt0+pp-3*nx)))));
    d_Gt[0][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(Gt0+pp+1*(nx*ny)), VLOAD(Gt0+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(Gt0+pp+2*(nx*ny)), VLOAD(Gt0+pp-2*(nx*ny))), VSUB(VLOAD(Gt0+pp+3*(nx*ny)), VLOAD(Gt0+pp-3*(nx*ny))))));
    d_Gt[1][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(Gt1+pp+1), VLOAD(Gt1+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(Gt1+pp+2), VLOAD(Gt1+pp-2)), VSUB(VLOAD(Gt1+pp+3), VLOAD(Gt1+pp-3)))));
    d_Gt[1][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(Gt1+pp+1*nx), VLOAD(Gt1+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(Gt1+pp+2*nx), VLOAD(Gt1+pp-2*nx)), VSUB(VLOAD(Gt1+pp+3*nx), VLOAD(Gt1+pp-3*nx)))));
    d_Gt[1][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(Gt1+pp+1*(nx*ny)), VLOAD(Gt1+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(Gt1+pp+2*(nx*ny)), VLOAD(Gt1+pp-2*(nx*ny))), VSUB(VLOAD(Gt1+pp+3*(nx*ny)), VLOAD(Gt1+pp-3*(nx*ny))))));
    d_Gt[2][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(Gt2+pp+1), VLOAD(Gt2+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(Gt2+pp+2), VLOAD(Gt2+pp-2)), VSUB(VLOAD(Gt2+pp+3), VLOAD(Gt2+pp-3)))));
    d_Gt[2][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(Gt2+pp+1*nx), VLOAD(Gt2+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(Gt2+pp+2*nx), VLOAD(Gt2+pp-2*nx)), VSUB(VLOAD(Gt2+pp+3*nx), VLOAD(Gt2+pp-3*nx)))));
    d_Gt[2][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(Gt2+pp+1*(nx*ny)), VLOAD(Gt2+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(Gt2+pp+2*(nx*ny)), VLOAD(Gt2+pp-2*(nx*ny))), VSUB(VLOAD(Gt2+pp+3*(nx*ny)), VLOAD(Gt2+pp-3*(nx*ny))))));
    VEC d_B[3][3];
    d_B[0][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(B0+pp+1), VLOAD(B0+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(B0+pp+2), VLOAD(B0+pp-2)), VSUB(VLOAD(B0+pp+3), VLOAD(B0+pp-3)))));
    d_B[0][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(B0+pp+1*nx), VLOAD(B0+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(B0+pp+2*nx), VLOAD(B0+pp-2*nx)), VSUB(VLOAD(B0+pp+3*nx), VLOAD(B0+pp-3*nx)))));
    d_B[0][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(B0+pp+1*(nx*ny)), VLOAD(B0+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(B0+pp+2*(nx*ny)), VLOAD(B0+pp-2*(nx*ny))), VSUB(VLOAD(B0+pp+3*(nx*ny)), VLOAD(B0+pp-3*(nx*ny))))));
    d_B[1][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(B1+pp+1), VLOAD(B1+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(B1+pp+2), VLOAD(B1+pp-2)), VSUB(VLOAD(B1+pp+3), VLOAD(B1+pp-3)))));
    d_B[1][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(B1+pp+1*nx), VLOAD(B1+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(B1+pp+2*nx), VLOAD(B1+pp-2*nx)), VSUB(VLOAD(B1+pp+3*nx), VLOAD(B1+pp-3*nx)))));
    d_B[1][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(B1+pp+1*(nx*ny)), VLOAD(B1+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(B1+pp+2*(nx*ny)), VLOAD(B1+pp-2*(nx*ny))), VSUB(VLOAD(B1+pp+3*(nx*ny)), VLOAD(B1+pp-3*(nx*ny))))));
    d_B[2][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(B2+pp+1), VLOAD(B2+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(B2+pp+2), VLOAD(B2+pp-2)), VSUB(VLOAD(B2+pp+3), VLOAD(B2+pp-3)))));
    d_B[2][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(B2+pp+1*nx), VLOAD(B2+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(B2+pp+2*nx), VLOAD(B2+pp-2*nx)), VSUB(VLOAD(B2+pp+3*nx), VLOAD(B2+pp-3*nx)))));
    d_B[2][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(B2+pp+1*(nx*ny)), VLOAD(B2+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(B2+pp+2*(nx*ny)), VLOAD(B2+pp-2*(nx*ny))), VSUB(VLOAD(B2+pp+3*(nx*ny)), VLOAD(B2+pp-3*(nx*ny))))));
    VEC d_gt[3][3][3];
    VEC d_At[3][3][3];
    d_gt[0][0][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(gt0+pp+1), VLOAD(gt0+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(gt0+pp+2), VLOAD(gt0+pp-2)), VSUB(VLOAD(gt0+pp+3), VLOAD(gt0+pp-3)))));
    d_At[0][0][0] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(At0+pp+1), VLOAD(At0+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(At0+pp+2), VLOAD(At0+pp-2)), VSUB(VLOAD(At0+pp+3), VLOAD(At0+pp-3)))));
    d_gt[0][0][1] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(gt1+pp+1), VLOAD(gt1+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(gt1+pp+2), VLOAD(gt1+pp-2)), VSUB(VLOAD(gt1+pp+3), VLOAD(gt1+pp-3)))));
    d_gt[0][1][0] = d_gt[0][0][1];
    d_At[0][0][1] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(At1+pp+1), VLOAD(At1+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(At1+pp+2), VLOAD(At1+pp-2)), VSUB(VLOAD(At1+pp+3), VLOAD(At1+pp-3)))));
    d_At[0][1][0] = d_At[0][0][1];
    d_gt[0][0][2] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(gt2+pp+1), VLOAD(gt2+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(gt2+pp+2), VLOAD(gt2+pp-2)), VSUB(VLOAD(gt2+pp+3), VLOAD(gt2+pp-3)))));
    d_gt[0][2][0] = d_gt[0][0][2];
    d_At[0][0][2] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(At2+pp+1), VLOAD(At2+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(At2+pp+2), VLOAD(At2+pp-2)), VSUB(VLOAD(At2+pp+3), VLOAD(At2+pp-3)))));
    d_At[0][2][0] = d_At[0][0][2];
    d_gt[0][1][1] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(gt3+pp+1), VLOAD(gt3+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(gt3+pp+2), VLOAD(gt3+pp-2)), VSUB(VLOAD(gt3+pp+3), VLOAD(gt3+pp-3)))));
    d_At[0][1][1] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(At3+pp+1), VLOAD(At3+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(At3+pp+2), VLOAD(At3+pp-2)), VSUB(VLOAD(At3+pp+3), VLOAD(At3+pp-3)))));
    d_gt[0][1][2] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(gt4+pp+1), VLOAD(gt4+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(gt4+pp+2), VLOAD(gt4+pp-2)), VSUB(VLOAD(gt4+pp+3), VLOAD(gt4+pp-3)))));
    d_gt[0][2][1] = d_gt[0][1][2];
    d_At[0][1][2] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(At4+pp+1), VLOAD(At4+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(At4+pp+2), VLOAD(At4+pp-2)), VSUB(VLOAD(At4+pp+3), VLOAD(At4+pp-3)))));
    d_At[0][2][1] = d_At[0][1][2];
    d_gt[0][2][2] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(gt5+pp+1), VLOAD(gt5+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(gt5+pp+2), VLOAD(gt5+pp-2)), VSUB(VLOAD(gt5+pp+3), VLOAD(gt5+pp-3)))));
    d_At[0][2][2] = VMUL(VSET(idx60), VFMA(VSET(45.0), VSUB(VLOAD(At5+pp+1), VLOAD(At5+pp-1)), VFMA(VSET(-9.0), VSUB(VLOAD(At5+pp+2), VLOAD(At5+pp-2)), VSUB(VLOAD(At5+pp+3), VLOAD(At5+pp-3)))));
    d_gt[1][0][0] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(gt0+pp+1*nx), VLOAD(gt0+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(gt0+pp+2*nx), VLOAD(gt0+pp-2*nx)), VSUB(VLOAD(gt0+pp+3*nx), VLOAD(gt0+pp-3*nx)))));
    d_At[1][0][0] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(At0+pp+1*nx), VLOAD(At0+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(At0+pp+2*nx), VLOAD(At0+pp-2*nx)), VSUB(VLOAD(At0+pp+3*nx), VLOAD(At0+pp-3*nx)))));
    d_gt[1][0][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(gt1+pp+1*nx), VLOAD(gt1+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(gt1+pp+2*nx), VLOAD(gt1+pp-2*nx)), VSUB(VLOAD(gt1+pp+3*nx), VLOAD(gt1+pp-3*nx)))));
    d_gt[1][1][0] = d_gt[1][0][1];
    d_At[1][0][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(At1+pp+1*nx), VLOAD(At1+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(At1+pp+2*nx), VLOAD(At1+pp-2*nx)), VSUB(VLOAD(At1+pp+3*nx), VLOAD(At1+pp-3*nx)))));
    d_At[1][1][0] = d_At[1][0][1];
    d_gt[1][0][2] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(gt2+pp+1*nx), VLOAD(gt2+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(gt2+pp+2*nx), VLOAD(gt2+pp-2*nx)), VSUB(VLOAD(gt2+pp+3*nx), VLOAD(gt2+pp-3*nx)))));
    d_gt[1][2][0] = d_gt[1][0][2];
    d_At[1][0][2] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(At2+pp+1*nx), VLOAD(At2+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(At2+pp+2*nx), VLOAD(At2+pp-2*nx)), VSUB(VLOAD(At2+pp+3*nx), VLOAD(At2+pp-3*nx)))));
    d_At[1][2][0] = d_At[1][0][2];
    d_gt[1][1][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(gt3+pp+1*nx), VLOAD(gt3+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(gt3+pp+2*nx), VLOAD(gt3+pp-2*nx)), VSUB(VLOAD(gt3+pp+3*nx), VLOAD(gt3+pp-3*nx)))));
    d_At[1][1][1] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(At3+pp+1*nx), VLOAD(At3+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(At3+pp+2*nx), VLOAD(At3+pp-2*nx)), VSUB(VLOAD(At3+pp+3*nx), VLOAD(At3+pp-3*nx)))));
    d_gt[1][1][2] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(gt4+pp+1*nx), VLOAD(gt4+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(gt4+pp+2*nx), VLOAD(gt4+pp-2*nx)), VSUB(VLOAD(gt4+pp+3*nx), VLOAD(gt4+pp-3*nx)))));
    d_gt[1][2][1] = d_gt[1][1][2];
    d_At[1][1][2] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(At4+pp+1*nx), VLOAD(At4+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(At4+pp+2*nx), VLOAD(At4+pp-2*nx)), VSUB(VLOAD(At4+pp+3*nx), VLOAD(At4+pp-3*nx)))));
    d_At[1][2][1] = d_At[1][1][2];
    d_gt[1][2][2] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(gt5+pp+1*nx), VLOAD(gt5+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(gt5+pp+2*nx), VLOAD(gt5+pp-2*nx)), VSUB(VLOAD(gt5+pp+3*nx), VLOAD(gt5+pp-3*nx)))));
    d_At[1][2][2] = VMUL(VSET(idy60), VFMA(VSET(45.0), VSUB(VLOAD(At5+pp+1*nx), VLOAD(At5+pp-1*nx)), VFMA(VSET(-9.0), VSUB(VLOAD(At5+pp+2*nx), VLOAD(At5+pp-2*nx)), VSUB(VLOAD(At5+pp+3*nx), VLOAD(At5+pp-3*nx)))));
    d_gt[2][0][0] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(gt0+pp+1*(nx*ny)), VLOAD(gt0+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(gt0+pp+2*(nx*ny)), VLOAD(gt0+pp-2*(nx*ny))), VSUB(VLOAD(gt0+pp+3*(nx*ny)), VLOAD(gt0+pp-3*(nx*ny))))));
    d_At[2][0][0] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(At0+pp+1*(nx*ny)), VLOAD(At0+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(At0+pp+2*(nx*ny)), VLOAD(At0+pp-2*(nx*ny))), VSUB(VLOAD(At0+pp+3*(nx*ny)), VLOAD(At0+pp-3*(nx*ny))))));
    d_gt[2][0][1] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(gt1+pp+1*(nx*ny)), VLOAD(gt1+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(gt1+pp+2*(nx*ny)), VLOAD(gt1+pp-2*(nx*ny))), VSUB(VLOAD(gt1+pp+3*(nx*ny)), VLOAD(gt1+pp-3*(nx*ny))))));
    d_gt[2][1][0] = d_gt[2][0][1];
    d_At[2][0][1] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(At1+pp+1*(nx*ny)), VLOAD(At1+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(At1+pp+2*(nx*ny)), VLOAD(At1+pp-2*(nx*ny))), VSUB(VLOAD(At1+pp+3*(nx*ny)), VLOAD(At1+pp-3*(nx*ny))))));
    d_At[2][1][0] = d_At[2][0][1];
    d_gt[2][0][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(gt2+pp+1*(nx*ny)), VLOAD(gt2+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(gt2+pp+2*(nx*ny)), VLOAD(gt2+pp-2*(nx*ny))), VSUB(VLOAD(gt2+pp+3*(nx*ny)), VLOAD(gt2+pp-3*(nx*ny))))));
    d_gt[2][2][0] = d_gt[2][0][2];
    d_At[2][0][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(At2+pp+1*(nx*ny)), VLOAD(At2+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(At2+pp+2*(nx*ny)), VLOAD(At2+pp-2*(nx*ny))), VSUB(VLOAD(At2+pp+3*(nx*ny)), VLOAD(At2+pp-3*(nx*ny))))));
    d_At[2][2][0] = d_At[2][0][2];
    d_gt[2][1][1] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(gt3+pp+1*(nx*ny)), VLOAD(gt3+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(gt3+pp+2*(nx*ny)), VLOAD(gt3+pp-2*(nx*ny))), VSUB(VLOAD(gt3+pp+3*(nx*ny)), VLOAD(gt3+pp-3*(nx*ny))))));
    d_At[2][1][1] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(At3+pp+1*(nx*ny)), VLOAD(At3+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(At3+pp+2*(nx*ny)), VLOAD(At3+pp-2*(nx*ny))), VSUB(VLOAD(At3+pp+3*(nx*ny)), VLOAD(At3+pp-3*(nx*ny))))));
    d_gt[2][1][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(gt4+pp+1*(nx*ny)), VLOAD(gt4+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(gt4+pp+2*(nx*ny)), VLOAD(gt4+pp-2*(nx*ny))), VSUB(VLOAD(gt4+pp+3*(nx*ny)), VLOAD(gt4+pp-3*(nx*ny))))));
    d_gt[2][2][1] = d_gt[2][1][2];
    d_At[2][1][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(At4+pp+1*(nx*ny)), VLOAD(At4+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(At4+pp+2*(nx*ny)), VLOAD(At4+pp-2*(nx*ny))), VSUB(VLOAD(At4+pp+3*(nx*ny)), VLOAD(At4+pp-3*(nx*ny))))));
    d_At[2][2][1] = d_At[2][1][2];
    d_gt[2][2][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(gt5+pp+1*(nx*ny)), VLOAD(gt5+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(gt5+pp+2*(nx*ny)), VLOAD(gt5+pp-2*(nx*ny))), VSUB(VLOAD(gt5+pp+3*(nx*ny)), VLOAD(gt5+pp-3*(nx*ny))))));
    d_At[2][2][2] = VMUL(VSET(idz60), VFMA(VSET(45.0), VSUB(VLOAD(At5+pp+1*(nx*ny)), VLOAD(At5+pp-1*(nx*ny))), VFMA(VSET(-9.0), VSUB(VLOAD(At5+pp+2*(nx*ny)), VLOAD(At5+pp-2*(nx*ny))), VSUB(VLOAD(At5+pp+3*(nx*ny)), VLOAD(At5+pp-3*(nx*ny))))));
    VEC d2_al[3][3], d2_ch[3][3];
    d2_al[0][0] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(alpha+pp-3), VLOAD(alpha+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(alpha+pp-2), VLOAD(alpha+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(alpha+pp-1), VLOAD(alpha+pp+1)), VMUL(VSET(-490.0), VLOAD(alpha+pp))))));
    d2_ch[0][0] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(chi+pp-3), VLOAD(chi+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(chi+pp-2), VLOAD(chi+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(chi+pp-1), VLOAD(chi+pp+1)), VMUL(VSET(-490.0), VLOAD(chi+pp))))));
    d2_al[0][1] = VLOAD(d2_al_p[1]+pp);
    d2_ch[0][1] = VLOAD(d2_ch_p[1]+pp);
    d2_al[1][0] = d2_al[0][1];
    d2_ch[1][0] = d2_ch[0][1];
    d2_al[0][2] = VLOAD(d2_al_p[2]+pp);
    d2_ch[0][2] = VLOAD(d2_ch_p[2]+pp);
    d2_al[2][0] = d2_al[0][2];
    d2_ch[2][0] = d2_ch[0][2];
    d2_al[1][1] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(alpha+pp-3*nx), VLOAD(alpha+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(alpha+pp-2*nx), VLOAD(alpha+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(alpha+pp-1*nx), VLOAD(alpha+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(alpha+pp))))));
    d2_ch[1][1] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(chi+pp-3*nx), VLOAD(chi+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(chi+pp-2*nx), VLOAD(chi+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(chi+pp-1*nx), VLOAD(chi+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(chi+pp))))));
    d2_al[1][2] = VLOAD(d2_al_p[4]+pp);
    d2_ch[1][2] = VLOAD(d2_ch_p[4]+pp);
    d2_al[2][1] = d2_al[1][2];
    d2_ch[2][1] = d2_ch[1][2];
    d2_al[2][2] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(alpha+pp-3*(nx*ny)), VLOAD(alpha+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(alpha+pp-2*(nx*ny)), VLOAD(alpha+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(alpha+pp-1*(nx*ny)), VLOAD(alpha+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(alpha+pp))))));
    d2_ch[2][2] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(chi+pp-3*(nx*ny)), VLOAD(chi+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(chi+pp-2*(nx*ny)), VLOAD(chi+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(chi+pp-1*(nx*ny)), VLOAD(chi+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(chi+pp))))));
    VEC d2_be[3][3][3];
    d2_be[0][0][0] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(beta0+pp-3), VLOAD(beta0+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(beta0+pp-2), VLOAD(beta0+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(beta0+pp-1), VLOAD(beta0+pp+1)), VMUL(VSET(-490.0), VLOAD(beta0+pp))))));
    d2_be[0][0][1] = VLOAD(d2_be_p[0][1]+pp);
    d2_be[0][1][0] = d2_be[0][0][1];
    d2_be[0][0][2] = VLOAD(d2_be_p[0][2]+pp);
    d2_be[0][2][0] = d2_be[0][0][2];
    d2_be[0][1][1] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(beta0+pp-3*nx), VLOAD(beta0+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(beta0+pp-2*nx), VLOAD(beta0+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(beta0+pp-1*nx), VLOAD(beta0+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(beta0+pp))))));
    d2_be[0][1][2] = VLOAD(d2_be_p[0][4]+pp);
    d2_be[0][2][1] = d2_be[0][1][2];
    d2_be[0][2][2] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(beta0+pp-3*(nx*ny)), VLOAD(beta0+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(beta0+pp-2*(nx*ny)), VLOAD(beta0+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(beta0+pp-1*(nx*ny)), VLOAD(beta0+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(beta0+pp))))));
    d2_be[1][0][0] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(beta1+pp-3), VLOAD(beta1+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(beta1+pp-2), VLOAD(beta1+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(beta1+pp-1), VLOAD(beta1+pp+1)), VMUL(VSET(-490.0), VLOAD(beta1+pp))))));
    d2_be[1][0][1] = VLOAD(d2_be_p[1][1]+pp);
    d2_be[1][1][0] = d2_be[1][0][1];
    d2_be[1][0][2] = VLOAD(d2_be_p[1][2]+pp);
    d2_be[1][2][0] = d2_be[1][0][2];
    d2_be[1][1][1] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(beta1+pp-3*nx), VLOAD(beta1+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(beta1+pp-2*nx), VLOAD(beta1+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(beta1+pp-1*nx), VLOAD(beta1+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(beta1+pp))))));
    d2_be[1][1][2] = VLOAD(d2_be_p[1][4]+pp);
    d2_be[1][2][1] = d2_be[1][1][2];
    d2_be[1][2][2] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(beta1+pp-3*(nx*ny)), VLOAD(beta1+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(beta1+pp-2*(nx*ny)), VLOAD(beta1+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(beta1+pp-1*(nx*ny)), VLOAD(beta1+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(beta1+pp))))));
    d2_be[2][0][0] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(beta2+pp-3), VLOAD(beta2+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(beta2+pp-2), VLOAD(beta2+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(beta2+pp-1), VLOAD(beta2+pp+1)), VMUL(VSET(-490.0), VLOAD(beta2+pp))))));
    d2_be[2][0][1] = VLOAD(d2_be_p[2][1]+pp);
    d2_be[2][1][0] = d2_be[2][0][1];
    d2_be[2][0][2] = VLOAD(d2_be_p[2][2]+pp);
    d2_be[2][2][0] = d2_be[2][0][2];
    d2_be[2][1][1] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(beta2+pp-3*nx), VLOAD(beta2+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(beta2+pp-2*nx), VLOAD(beta2+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(beta2+pp-1*nx), VLOAD(beta2+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(beta2+pp))))));
    d2_be[2][1][2] = VLOAD(d2_be_p[2][4]+pp);
    d2_be[2][2][1] = d2_be[2][1][2];
    d2_be[2][2][2] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(beta2+pp-3*(nx*ny)), VLOAD(beta2+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(beta2+pp-2*(nx*ny)), VLOAD(beta2+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(beta2+pp-1*(nx*ny)), VLOAD(beta2+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(beta2+pp))))));
    VEC d2_gt[3][3][3][3];
    d2_gt[0][0][0][0] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(gt0+pp-3), VLOAD(gt0+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(gt0+pp-2), VLOAD(gt0+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(gt0+pp-1), VLOAD(gt0+pp+1)), VMUL(VSET(-490.0), VLOAD(gt0+pp))))));
    d2_gt[0][1][0][0] = VLOAD(d2_gt_p[0][1]+pp);
    d2_gt[1][0][0][0] = d2_gt[0][1][0][0];
    d2_gt[0][2][0][0] = VLOAD(d2_gt_p[0][2]+pp);
    d2_gt[2][0][0][0] = d2_gt[0][2][0][0];
    d2_gt[1][1][0][0] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(gt0+pp-3*nx), VLOAD(gt0+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(gt0+pp-2*nx), VLOAD(gt0+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(gt0+pp-1*nx), VLOAD(gt0+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(gt0+pp))))));
    d2_gt[1][2][0][0] = VLOAD(d2_gt_p[0][4]+pp);
    d2_gt[2][1][0][0] = d2_gt[1][2][0][0];
    d2_gt[2][2][0][0] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(gt0+pp-3*(nx*ny)), VLOAD(gt0+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(gt0+pp-2*(nx*ny)), VLOAD(gt0+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(gt0+pp-1*(nx*ny)), VLOAD(gt0+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(gt0+pp))))));
    d2_gt[0][0][0][1] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(gt1+pp-3), VLOAD(gt1+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(gt1+pp-2), VLOAD(gt1+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(gt1+pp-1), VLOAD(gt1+pp+1)), VMUL(VSET(-490.0), VLOAD(gt1+pp))))));
    d2_gt[0][0][1][0] = d2_gt[0][0][0][1];
    d2_gt[0][1][0][1] = VLOAD(d2_gt_p[1][1]+pp);
    d2_gt[1][0][0][1] = d2_gt[0][1][0][1];
    d2_gt[0][1][1][0] = d2_gt[0][1][0][1];
    d2_gt[1][0][1][0] = d2_gt[0][1][0][1];
    d2_gt[0][2][0][1] = VLOAD(d2_gt_p[1][2]+pp);
    d2_gt[2][0][0][1] = d2_gt[0][2][0][1];
    d2_gt[0][2][1][0] = d2_gt[0][2][0][1];
    d2_gt[2][0][1][0] = d2_gt[0][2][0][1];
    d2_gt[1][1][0][1] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(gt1+pp-3*nx), VLOAD(gt1+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(gt1+pp-2*nx), VLOAD(gt1+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(gt1+pp-1*nx), VLOAD(gt1+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(gt1+pp))))));
    d2_gt[1][1][1][0] = d2_gt[1][1][0][1];
    d2_gt[1][2][0][1] = VLOAD(d2_gt_p[1][4]+pp);
    d2_gt[2][1][0][1] = d2_gt[1][2][0][1];
    d2_gt[1][2][1][0] = d2_gt[1][2][0][1];
    d2_gt[2][1][1][0] = d2_gt[1][2][0][1];
    d2_gt[2][2][0][1] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(gt1+pp-3*(nx*ny)), VLOAD(gt1+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(gt1+pp-2*(nx*ny)), VLOAD(gt1+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(gt1+pp-1*(nx*ny)), VLOAD(gt1+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(gt1+pp))))));
    d2_gt[2][2][1][0] = d2_gt[2][2][0][1];
    d2_gt[0][0][0][2] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(gt2+pp-3), VLOAD(gt2+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(gt2+pp-2), VLOAD(gt2+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(gt2+pp-1), VLOAD(gt2+pp+1)), VMUL(VSET(-490.0), VLOAD(gt2+pp))))));
    d2_gt[0][0][2][0] = d2_gt[0][0][0][2];
    d2_gt[0][1][0][2] = VLOAD(d2_gt_p[2][1]+pp);
    d2_gt[1][0][0][2] = d2_gt[0][1][0][2];
    d2_gt[0][1][2][0] = d2_gt[0][1][0][2];
    d2_gt[1][0][2][0] = d2_gt[0][1][0][2];
    d2_gt[0][2][0][2] = VLOAD(d2_gt_p[2][2]+pp);
    d2_gt[2][0][0][2] = d2_gt[0][2][0][2];
    d2_gt[0][2][2][0] = d2_gt[0][2][0][2];
    d2_gt[2][0][2][0] = d2_gt[0][2][0][2];
    d2_gt[1][1][0][2] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(gt2+pp-3*nx), VLOAD(gt2+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(gt2+pp-2*nx), VLOAD(gt2+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(gt2+pp-1*nx), VLOAD(gt2+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(gt2+pp))))));
    d2_gt[1][1][2][0] = d2_gt[1][1][0][2];
    d2_gt[1][2][0][2] = VLOAD(d2_gt_p[2][4]+pp);
    d2_gt[2][1][0][2] = d2_gt[1][2][0][2];
    d2_gt[1][2][2][0] = d2_gt[1][2][0][2];
    d2_gt[2][1][2][0] = d2_gt[1][2][0][2];
    d2_gt[2][2][0][2] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(gt2+pp-3*(nx*ny)), VLOAD(gt2+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(gt2+pp-2*(nx*ny)), VLOAD(gt2+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(gt2+pp-1*(nx*ny)), VLOAD(gt2+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(gt2+pp))))));
    d2_gt[2][2][2][0] = d2_gt[2][2][0][2];
    d2_gt[0][0][1][1] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(gt3+pp-3), VLOAD(gt3+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(gt3+pp-2), VLOAD(gt3+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(gt3+pp-1), VLOAD(gt3+pp+1)), VMUL(VSET(-490.0), VLOAD(gt3+pp))))));
    d2_gt[0][1][1][1] = VLOAD(d2_gt_p[3][1]+pp);
    d2_gt[1][0][1][1] = d2_gt[0][1][1][1];
    d2_gt[0][2][1][1] = VLOAD(d2_gt_p[3][2]+pp);
    d2_gt[2][0][1][1] = d2_gt[0][2][1][1];
    d2_gt[1][1][1][1] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(gt3+pp-3*nx), VLOAD(gt3+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(gt3+pp-2*nx), VLOAD(gt3+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(gt3+pp-1*nx), VLOAD(gt3+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(gt3+pp))))));
    d2_gt[1][2][1][1] = VLOAD(d2_gt_p[3][4]+pp);
    d2_gt[2][1][1][1] = d2_gt[1][2][1][1];
    d2_gt[2][2][1][1] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(gt3+pp-3*(nx*ny)), VLOAD(gt3+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(gt3+pp-2*(nx*ny)), VLOAD(gt3+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(gt3+pp-1*(nx*ny)), VLOAD(gt3+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(gt3+pp))))));
    d2_gt[0][0][1][2] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(gt4+pp-3), VLOAD(gt4+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(gt4+pp-2), VLOAD(gt4+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(gt4+pp-1), VLOAD(gt4+pp+1)), VMUL(VSET(-490.0), VLOAD(gt4+pp))))));
    d2_gt[0][0][2][1] = d2_gt[0][0][1][2];
    d2_gt[0][1][1][2] = VLOAD(d2_gt_p[4][1]+pp);
    d2_gt[1][0][1][2] = d2_gt[0][1][1][2];
    d2_gt[0][1][2][1] = d2_gt[0][1][1][2];
    d2_gt[1][0][2][1] = d2_gt[0][1][1][2];
    d2_gt[0][2][1][2] = VLOAD(d2_gt_p[4][2]+pp);
    d2_gt[2][0][1][2] = d2_gt[0][2][1][2];
    d2_gt[0][2][2][1] = d2_gt[0][2][1][2];
    d2_gt[2][0][2][1] = d2_gt[0][2][1][2];
    d2_gt[1][1][1][2] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(gt4+pp-3*nx), VLOAD(gt4+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(gt4+pp-2*nx), VLOAD(gt4+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(gt4+pp-1*nx), VLOAD(gt4+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(gt4+pp))))));
    d2_gt[1][1][2][1] = d2_gt[1][1][1][2];
    d2_gt[1][2][1][2] = VLOAD(d2_gt_p[4][4]+pp);
    d2_gt[2][1][1][2] = d2_gt[1][2][1][2];
    d2_gt[1][2][2][1] = d2_gt[1][2][1][2];
    d2_gt[2][1][2][1] = d2_gt[1][2][1][2];
    d2_gt[2][2][1][2] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(gt4+pp-3*(nx*ny)), VLOAD(gt4+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(gt4+pp-2*(nx*ny)), VLOAD(gt4+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(gt4+pp-1*(nx*ny)), VLOAD(gt4+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(gt4+pp))))));
    d2_gt[2][2][2][1] = d2_gt[2][2][1][2];
    d2_gt[0][0][2][2] = VMUL(VSET(idx2_180), VFMA(VSET(2.0), VADD(VLOAD(gt5+pp-3), VLOAD(gt5+pp+3)), VFMA(VSET(-27.0), VADD(VLOAD(gt5+pp-2), VLOAD(gt5+pp+2)), VFMA(VSET(270.0), VADD(VLOAD(gt5+pp-1), VLOAD(gt5+pp+1)), VMUL(VSET(-490.0), VLOAD(gt5+pp))))));
    d2_gt[0][1][2][2] = VLOAD(d2_gt_p[5][1]+pp);
    d2_gt[1][0][2][2] = d2_gt[0][1][2][2];
    d2_gt[0][2][2][2] = VLOAD(d2_gt_p[5][2]+pp);
    d2_gt[2][0][2][2] = d2_gt[0][2][2][2];
    d2_gt[1][1][2][2] = VMUL(VSET(idy2_180), VFMA(VSET(2.0), VADD(VLOAD(gt5+pp-3*nx), VLOAD(gt5+pp+3*nx)), VFMA(VSET(-27.0), VADD(VLOAD(gt5+pp-2*nx), VLOAD(gt5+pp+2*nx)), VFMA(VSET(270.0), VADD(VLOAD(gt5+pp-1*nx), VLOAD(gt5+pp+1*nx)), VMUL(VSET(-490.0), VLOAD(gt5+pp))))));
    d2_gt[1][2][2][2] = VLOAD(d2_gt_p[5][4]+pp);
    d2_gt[2][1][2][2] = d2_gt[1][2][2][2];
    d2_gt[2][2][2][2] = VMUL(VSET(idz2_180), VFMA(VSET(2.0), VADD(VLOAD(gt5+pp-3*(nx*ny)), VLOAD(gt5+pp+3*(nx*ny))), VFMA(VSET(-27.0), VADD(VLOAD(gt5+pp-2*(nx*ny)), VLOAD(gt5+pp+2*(nx*ny))), VFMA(VSET(270.0), VADD(VLOAD(gt5+pp-1*(nx*ny)), VLOAD(gt5+pp+1*(nx*ny))), VMUL(VSET(-490.0), VLOAD(gt5+pp))))));
    // Advective = centered in this harness/dendrogr convention
    const VEC (* const ad_al) = d_al;
    const VEC (* const ad_ch) = d_ch;
    const VEC (* const ad_K)  = d_K;
    const VEC (* const ad_be)[3] = d_be;
    const VEC (* const ad_Gt)[3] = d_Gt;
    const VEC (* const ad_B)[3]  = d_B;
    const VEC (* const ad_gt)[3][3] = d_gt;
    const VEC (* const ad_At)[3][3] = d_At;
    
    // === L1: Inverse metric ===
    const VEC _half = VSET(0.5);
    const VEC _nhalf = VSET(-0.5);
    const VEC _inv3  = VSET(1.0/3.0);
    const VEC _w23   = VSET(-2.0/3.0);
    const VEC _two = VSET(2.0);
    const VEC det = VSUB(VADD(
        VMUL(gt[0][0], VSUB(VMUL(gt[1][1],gt[2][2]), VMUL(gt[1][2],gt[1][2]))),
        VMUL(gt[0][2], VSUB(VMUL(gt[0][1],gt[1][2]), VMUL(gt[1][1],gt[0][2])))),
        VMUL(gt[0][1], VSUB(VMUL(gt[0][1],gt[2][2]), VMUL(gt[1][2],gt[0][2]))));
    const VEC di = VDIV(VSET(1.0), det);
    VEC igt[3][3];
    igt[0][0] = VMUL(VSUB(VMUL(gt[1][1],gt[2][2]),VMUL(gt[1][2],gt[1][2])),di);
    igt[0][1] = VMUL(VSUB(VMUL(gt[0][2],gt[1][2]),VMUL(gt[0][1],gt[2][2])),di);
    igt[0][2] = VMUL(VSUB(VMUL(gt[0][1],gt[1][2]),VMUL(gt[0][2],gt[1][1])),di);
    igt[1][0] = igt[0][1];
    igt[1][1] = VMUL(VSUB(VMUL(gt[0][0],gt[2][2]),VMUL(gt[0][2],gt[0][2])),di);
    igt[1][2] = VMUL(VSUB(VMUL(gt[0][1],gt[0][2]),VMUL(gt[0][0],gt[1][2])),di);
    igt[2][0] = igt[0][2];
    igt[2][1] = igt[1][2];
    igt[2][2] = VMUL(VSUB(VMUL(gt[0][0],gt[1][1]),VMUL(gt[0][1],gt[0][1])),di);
    const VEC chi_inv = VDIV(VSET(1.0), ch);
    
    // === L2: First Christoffel ===
    VEC C1[3][3][3];
    for (int k = 0; k < 3; k++)
        for (int i = 0; i < 3; i++)
            for (int j = 0; j < 3; j++)
                C1[k][i][j] = VMUL(_half, VSUB(VADD(d_gt[j][k][i], d_gt[i][k][j]), d_gt[k][i][j]));
    
    // === L3: Second Christoffel ===
    VEC C2[3][3][3];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            for (int k = 0; k < 3; k++) {
                C2[i][j][k] = VFMA(igt[i][0], C1[0][j][k],
                               VFMA(igt[i][1], C1[1][j][k], VMUL(igt[i][2], C1[2][j][k])));
            }
    
    // === L4: Complete Christoffel ===
    VEC igt_dchi[3];
    for (int i = 0; i < 3; i++)
        igt_dchi[i] = VFMA(igt[i][0], d_ch[0],
                        VFMA(igt[i][1], d_ch[1], VMUL(igt[i][2], d_ch[2])));
    VEC C3[3][3][3];
    const VEC nhalf_chi_inv = VMUL(_nhalf, chi_inv);
    const VEC _zero = VSET(0.0);
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            for (int k = 0; k < 3; k++) {
                VEC t_ij = (i==j) ? d_ch[k] : _zero;
                VEC t_ik = (i==k) ? d_ch[j] : _zero;
                VEC corr = VSUB(VADD(t_ij, t_ik), VMUL(gt[j][k], igt_dchi[i]));
                C3[i][j][k] = VFMA(nhalf_chi_inv, corr, C2[i][j][k]);
            }
    
    // === L5: Ricci tensor ===
    VEC CalGt[3];
    for (int i = 0; i < 3; i++) {
        CalGt[i] = _zero;
        for (int k = 0; k < 3; k++)
            for (int l = 0; l < 3; l++)
                CalGt[i] = VFMA(igt[k][l], C2[i][k][l], CalGt[i]);
    }
    VEC Rt[3][3];
    for (int i = 0; i < 3; i++)
        for (int j = i; j < 3; j++) {
            VEC t1=_zero, t2=_zero, t3=_zero, t4=_zero;
            for (int l = 0; l < 3; l++)
                for (int m = 0; m < 3; m++)
                    t1 = VFMA(igt[l][m], d2_gt[l][m][i][j], t1);
            t1 = VMUL(_nhalf, t1);
            for (int k = 0; k < 3; k++)
                t2 = VADD(t2, VADD(VMUL(gt[k][i],d_Gt[k][j]), VMUL(gt[k][j],d_Gt[k][i])));
            t2 = VMUL(_half, t2);
            for (int k = 0; k < 3; k++)
                t3 = VFMA(CalGt[k], VADD(C1[i][j][k],C1[j][i][k]), t3);
            t3 = VMUL(_half, t3);
            for (int k = 0; k < 3; k++)
                for (int l = 0; l < 3; l++)
                    for (int m = 0; m < 3; m++)
                        t4 = VFMA(igt[l][m],
                              VADD(VADD(VMUL(C2[k][l][i],C1[j][k][m]),
                                         VMUL(C2[k][l][j],C1[i][k][m])),
                                   VMUL(C2[k][i][m],C1[k][l][j])), t4);
            Rt[i][j] = VADD(VADD(t1,t2), VADD(t3,t4));
            Rt[j][i] = Rt[i][j];
        }
    VEC C2_dc[3][3];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++) {
            C2_dc[i][j] = _zero;
            for (int k = 0; k < 3; k++)
                C2_dc[i][j] = VFMA(C2[k][j][i], d_ch[k], C2_dc[i][j]);
        }
    const VEC chi_inv2 = VMUL(chi_inv, chi_inv);
    VEC xRphi[3][3];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            xRphi[i][j] = VSUB(VMUL(VMUL(_half, chi_inv), VSUB(d2_ch[i][j], C2_dc[i][j])),
                                VMUL(VMUL(VSET(0.25), chi_inv2), VMUL(d_ch[i], d_ch[j])));
    VEC igt_d2chi = _zero, igt_dchi_dchi = _zero, CalGt_dchi = _zero;
    for (int k = 0; k < 3; k++) {
        CalGt_dchi = VFMA(CalGt[k], d_ch[k], CalGt_dchi);
        for (int l = 0; l < 3; l++) {
            igt_d2chi = VFMA(igt[k][l], d2_ch[k][l], igt_d2chi);
            igt_dchi_dchi = VFMA(igt[k][l], VMUL(d_ch[k], d_ch[l]), igt_dchi_dchi);
        }
    }
    const VEC scalar_part = VSUB(VSUB(igt_d2chi, VMUL(VSET(1.5), VMUL(chi_inv, igt_dchi_dchi))), CalGt_dchi);
    VEC R[3][3];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            R[i][j] = VADD(Rt[i][j], VADD(xRphi[i][j], VMUL(VMUL(_half, chi_inv), VMUL(gt[i][j], scalar_part))));
    
    // === L6: Derived quantities ===
    VEC At_UU[3][3];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++) {
            At_UU[i][j] = _zero;
            for (int k = 0; k < 3; k++)
                for (int l = 0; l < 3; l++)
                    At_UU[i][j] = VFMA(VMUL(igt[i][k], igt[j][l]), At[k][l], At_UU[i][j]);
        }
    VEC Aup[3][3];
    for (int k = 0; k < 3; k++)
        for (int j = 0; j < 3; j++) {
            Aup[k][j] = _zero;
            for (int l = 0; l < 3; l++)
                Aup[k][j] = VFMA(igt[k][l], At[l][j], Aup[k][j]);
        }
    VEC AikAkj[3][3];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++) {
            AikAkj[i][j] = _zero;
            for (int k = 0; k < 3; k++)
                AikAkj[i][j] = VFMA(At[i][k], Aup[k][j], AikAkj[i][j]);
        }
    VEC DiDj_a[3][3];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++) {
            DiDj_a[i][j] = d2_al[i][j];
            for (int l = 0; l < 3; l++)
                DiDj_a[i][j] = VSUB(DiDj_a[i][j], VMUL(C3[l][i][j], d_al[l]));
        }
    VEC trace_val = _zero;
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            trace_val = VFMA(igt[i][j], VSUB(VMUL(al, R[i][j]), DiDj_a[i][j]), trace_val);
    VEC tf[3][3];
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            tf[i][j] = VSUB(VSUB(VMUL(al, R[i][j]), DiDj_a[i][j]),
                             VMUL(gt[i][j], VMUL(trace_val, _inv3)));
    VEC At_sqr = _zero;
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            At_sqr = VFMA(At[i][j], At_UU[i][j], At_sqr);
    VEC lap_a = _zero;
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++) {
            VEC dd = d2_al[i][j];
            for (int l = 0; l < 3; l++)
                dd = VSUB(dd, VMUL(C3[l][i][j], d_al[l]));
            lap_a = VFMA(VMUL(ch, igt[i][j]), dd, lap_a);
        }
    const VEC div_be = VADD(VADD(d_be[0][0], d_be[1][1]), d_be[2][2]);
    
    // === L7: RHS assembly (stores to output arrays) ===
    {
        VEC beadal = VFMA(be[0], ad_al[0], VFMA(be[1], ad_al[1], VMUL(be[2], ad_al[2])));
        VEC out = VSUB(VMUL(VSET((double)lambda[0]), beadal), VMUL(_two, VMUL(al, Kv)));
    #ifdef BSSN_ENABLE_SSL_HD
        // SSL: shock-avoiding lapse correction
        //   a_rhs += -sqrt(chi) * h_ssl * (alpha - sqrt(chi)) * exp(-0.5*t^2/sig^2)
        // Constant factor per RHS call (t, h_ssl, sig_ssl are scalars in scope).
        const VEC _ssl_fac = VSET(-h_ssl * std::exp(-0.5*t*t/(sig_ssl*sig_ssl)));
        const VEC _sqrt_chi = VSQRT(ch);
        out = VFMA(_ssl_fac, VMUL(_sqrt_chi, VSUB(al, _sqrt_chi)), out);
    #endif
        VSTORE(a_rhs+pp, out);
    }
    {
        VEC fac = VMUL(VSET(0.75), VADD(VSET(lambda_f[0]), VMUL(VSET(lambda_f[1]), al)));
        double * const b_rhs_arr[3] = {b_rhs0, b_rhs1, b_rhs2};
        for (int i = 0; i < 3; i++) {
            VEC badbi = VFMA(be[0], ad_be[i][0], VFMA(be[1], ad_be[i][1], VMUL(be[2], ad_be[i][2])));
            VEC out = VADD(VMUL(fac, Bv[i]), VMUL(VSET((double)lambda[1]), badbi));
            VSTORE(b_rhs_arr[i]+pp, out);
        }
    }
    {
        double * const gt_rhs_arr[6] = {gt_rhs00, gt_rhs01, gt_rhs02, gt_rhs11, gt_rhs12, gt_rhs22};
        for (int i = 0; i < 3; i++)
            for (int j = i; j < 3; j++) {
                VEC lie = VMUL(_w23, VMUL(gt[i][j], div_be));
                for (int k = 0; k < 3; k++)
                    lie = VADD(lie, VADD(VADD(VMUL(be[k], ad_gt[k][i][j]), VMUL(gt[i][k], d_be[k][j])), VMUL(gt[k][j], d_be[k][i])));
                VEC out = VSUB(lie, VMUL(_two, VMUL(al, At[i][j])));
                VSTORE(gt_rhs_arr[cascade_sym_idx(i,j)]+pp, out);
            }
    }
    {
        VEC beadch = VFMA(be[0], ad_ch[0], VFMA(be[1], ad_ch[1], VMUL(be[2], ad_ch[2])));
        VEC term = VADD(VMUL(_w23, VMUL(ch, div_be)), VMUL(VSET(2.0/3.0), VMUL(ch, VMUL(al, Kv))));
        VEC chi_rhs_out = VADD(beadch, term);
    #ifdef BSSN_ENABLE_SSL_HD
        // CAHD: constraint-added Hamiltonian damping
        //   chi_rhs += -cahd_fac * ham / dt * chi
        //   ham = chi*R_scalar - At_sqr + (2/3)*K^2
        //   cahd_fac = BSSN_CAHD_C * dx^2 / (1 + 10*dx^2) (scalar per call)
        VEC _R_scalar = _zero;
        for (int i = 0; i < 3; i++)
            for (int j = 0; j < 3; j++)
                _R_scalar = VFMA(igt[i][j], R[i][j], _R_scalar);
        VEC _ham = VSUB(VFMA(ch, _R_scalar, VMUL(VSET(2.0/3.0), VMUL(Kv, Kv))), At_sqr);
        const VEC _cahd_coef = VSET(BSSN_CAHD_C * dx_i * dx_i / (1.0 + 10.0 * dx_i * dx_i) / dt);
        chi_rhs_out = VFMA(_cahd_coef, VMUL(_ham, ch), chi_rhs_out);
    #endif
        VSTORE(chi_rhs+pp, chi_rhs_out);
    }
    {
        double * const At_rhs_arr[6] = {At_rhs00, At_rhs01, At_rhs02, At_rhs11, At_rhs12, At_rhs22};
        for (int i = 0; i < 3; i++)
            for (int j = i; j < 3; j++) {
                VEC lie = VMUL(_w23, VMUL(At[i][j], div_be));
                for (int k = 0; k < 3; k++)
                    lie = VADD(lie, VADD(VADD(VMUL(be[k], ad_At[k][i][j]), VMUL(At[i][k], d_be[k][j])), VMUL(At[k][j], d_be[k][i])));
                VEC algeb = VADD(VMUL(ch, tf[i][j]), VMUL(al, VSUB(VMUL(Kv, At[i][j]), VMUL(_two, AikAkj[i][j]))));
                VSTORE(At_rhs_arr[cascade_sym_idx(i,j)]+pp, VADD(lie, algeb));
            }
    }
    {
        VEC beadK = VFMA(be[0], ad_K[0], VFMA(be[1], ad_K[1], VMUL(be[2], ad_K[2])));
        VEC out = VADD(VSUB(beadK, lap_a), VMUL(al, VADD(VMUL(Kv, VMUL(Kv, _inv3)), At_sqr)));
        VSTORE(K_rhs+pp, out);
    }
    VEC Gt_rhs_v[3];
    for (int i = 0; i < 3; i++) {
        VEC t1 = VFMA(be[0], ad_Gt[i][0], VFMA(be[1], ad_Gt[i][1], VMUL(be[2], ad_Gt[i][2])));
        VEC t2 = _zero;
        for (int j = 0; j < 3; j++) t2 = VFMA(CalGt[j], d_be[i][j], t2);
        t2 = VSUB(_zero, t2);
        VEC t3 = VMUL(VSET(2.0/3.0), VMUL(CalGt[i], div_be));
        VEC t4 = _zero;
        for (int j = 0; j < 3; j++)
            for (int k = 0; k < 3; k++)
                t4 = VADD(t4, VADD(VMUL(igt[j][k], d2_be[i][j][k]), VMUL(VMUL(igt[i][j], d2_be[k][j][k]), _inv3)));
        VEC t5 = _zero;
        for (int j = 0; j < 3; j++) t5 = VFMA(At_UU[i][j], d_al[j], t5);
        t5 = VMUL(VSET(-2.0), t5);
        VEC t6 = _zero;
        for (int j = 0; j < 3; j++)
            for (int k = 0; k < 3; k++)
                t6 = VFMA(C2[i][j][k], At_UU[j][k], t6);
        t6 = VMUL(VMUL(_two, al), t6);
        VEC t7 = _zero;
        for (int j = 0; j < 3; j++)
            t7 = VADD(t7, VADD(VMUL(VMUL(VSET(3.0), chi_inv), VMUL(At_UU[i][j], d_ch[j])),
                                VMUL(VSET(4.0/3.0), VMUL(igt[i][j], d_K[j]))));
        t7 = VMUL(VSUB(_zero, al), t7);
        Gt_rhs_v[i] = VADD(VADD(VADD(t1,t2), VADD(t3,t4)), VADD(VADD(t5,t6), t7));
    }
    VSTORE(Gt_rhs0+pp, Gt_rhs_v[0]);
    VSTORE(Gt_rhs1+pp, Gt_rhs_v[1]);
    VSTORE(Gt_rhs2+pp, Gt_rhs_v[2]);
    {
        double * const B_rhs_arr[3] = {B_rhs0, B_rhs1, B_rhs2};
        for (int i = 0; i < 3; i++) {
            VEC adB = VFMA(be[0], ad_B[i][0], VFMA(be[1], ad_B[i][1], VMUL(be[2], ad_B[i][2])));
            VEC adGt = VFMA(be[0], ad_Gt[i][0], VFMA(be[1], ad_Gt[i][1], VMUL(be[2], ad_Gt[i][2])));
            VEC out = VADD(VSUB(Gt_rhs_v[i], VMUL(eta, Bv[i])),
                            VSUB(VMUL(VSET((double)lambda[2]), adB), VMUL(VSET((double)lambda[3]), adGt)));
            VSTORE(B_rhs_arr[i]+pp, out);
        }
    }
}
